name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2 

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install melos
        run: dart pub global activate melos
      
      - name: Install dependencies
        run: melos bootstrap

      - name: Generate files 
        run: melos exec -c 1 --depends-on="build_runner" --no-flutter -- "dart run build_runner build --delete-conflicting-outputs"

      - name: Verify formatting
        run: melos exec -c 1 -- dart format --output=none --set-exit-if-changed .

      - name: Analyze
        run: melos exec -c 1 -- dart analyze .

      - name: Run dart test
        run: melos exec -c 1 --no-flutter -- dart test

      - name: Run flutter test
        run: melos exec -c 1 --flutter -- flutter test
